### ISSUE TITLE
minimax diffusion for datasets other than ImageNet?

### ISSUE THREAD

**Issue by zhengyu-su** [vimar-gu/MinimaxDiffusion#3]
Hi, I just saw that you have actually implemented multiple options for other datasets like CIFAR, MNIST, etc. I am trying to get CIFAR10 running, but the generated samples does not seem to be as expected. Do you maybe have any results shown for this just like for the ImageNet experiments? Would you also update the code at some point for the entire pipeline for other datasets?

**Comment by vimar-gu** [comment]
Thanks for the interest!
This project is mainly based on a DiT model pre-trained on ImageNet. And the DiT pipeline does not directly involve text prompts but uses the class indices of ImageNet for conditioning. So directly applying the project to other datasets may not receive good performance.
I've also tried more general pipelines like StableDiffusion. Some recent models like SDv2 also yield good generation results even without the fine-tuning. I adopted DiT mainly due to the convenience of fine-tuning (Compared with SDv2, DiT requires much less resource). So if there is sufficient resource, you can try SD. There can be more flexibility on the prompt design and dataset selection. 
Hope this addresses your concern :)
